# MQTT sensors from Airiana
binary_sensor:
  - platform: mqtt
    name: "Shower mode"
    state_topic: "airiana"
    value_template: "{{ value_json.shower }}"
    payload_off: "false"
    payload_on:  "true"
  - platform: mqtt
    name: "Cooling mode"
    state_topic: "airiana"
    value_template: "{{ value_json.coolingMode }}"
    payload_off: "false"
    payload_on:  "true"
    
sensor:

  - platform: mqtt
    name: "Exhaust"
    state_topic: "airiana"
    value_template: "{{ value_json.exhaust | round(2)}}"
    unit_of_measurement: "  C"

  - platform: mqtt
    name: "Rotor speed"
    state_topic: "airiana"
    value_template: "{{ value_json.rotorSpeed }}"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Inlet"
    state_topic: "airiana"
    device_class: "temperature"
    unit_of_measurement: "°C"
    value_template: "{{ value_json.inlet | round(2) }}"

  - platform: mqtt
    name: "Extract"
    state_topic: "airiana"
    device_class: "temperature"
    unit_of_measurement: "°C"
    value_template: "{{ value_json.extract | round(2) }}"

  - platform: mqtt
    name: "Supply"
    state_topic: "airiana"
    device_class: "temperature"
    unit_of_measurement: "°C"
    value_template: "{{ value_json.supply | round(2) }}"

  - platform: mqtt
    name: "ref RH%"
    state_topic: "airiana"
    device_class: "humidity"
    unit_of_measurement: "%"
    value_template: "{{ value_json.referenceHumidity | round(2) }}"

  - platform: mqtt
    name: "RH%"
    state_topic: "airiana"
    device_class: "humidity"
    unit_of_measurement: "%"
    value_template: "{{ value_json.measuredHumidity | round(2) }}"

  - platform: mqtt
    name: "Ambient Pressure"
    state_topic: "airiana"
    device_class: "pressure"
    unit_of_measurement: "hPa"
    value_template: "{{ value_json.pressure | round(0) }}"

  - platform: mqtt
    name: "Exchanger Efficiency"
    state_topic: "airiana"
    unit_of_measurement: "%"
    value_template: "{{ value_json.efficiency | round(0) }}"

  - platform: mqtt
    name: "Filter remaining"
    state_topic: "airiana"
    unit_of_measurement: "%"
    value_template: "{{ value_json.filterPercentRemaining | round(0) }}"

  - platform: mqtt
    name: "Filter time"
    state_topic: "airiana"
    unit_of_measurement: "days"
    value_template: "{{ value_json.filterInstalledDays | round(0) }}"

  - platform: mqtt
    name: "Electric power"
    state_topic: "airiana"
    unit_of_measurement: "W"
    value_template: "{{ value_json.electricPower | round(0) }}"

  - platform: mqtt
    name: "Rotor active"
    state_topic: "airiana"
    unit_of_measurement: ""
    value_template: "{{ value_json.rotorActive }}"

#Rest commands to airiana
rest_command:
  toggle_pressure:
    url: "http://airiana.local:8000/command?7"
    method: "get"
  toggle_auto:
    url: "http://airiana.local:8000/command?1"
    method: "get"
  force_vent:
    url: "http://airiana.local:8000/command?8"
    method: "get"
  fire_start:
    url: "http://airiana.local:8000/command?9"
    method: "get"
  vent_high:
    url: "http://airiana.local:8000/command?99"
    method: "get"
  vent_norm:
    url: "http://airiana.local:8000/command?98"
    method: "get"
  vent_low:
    url: "http://airiana.local:8000/command?97"
    method: "get"
  toggle_exchanger:
    url: "http://airiana.local:8000/command?0"
    method: "get"
  auto_off:
    url: "http://airiana.local:8000/command?14"
    method: "get"


