#!/usr/bin/python3
import json
import sys

try:
    with open("coeficients.json", "r") as file:
        a = json.load(file)
        # Convert string keys back to integers for processing
        a = {int(k): {int(dk): float(dv) for dk, dv in v.items()} for k, v in a.items()}
except FileNotFoundError:
    a = {0: {}, 1: {}, 2: {}, 3: {}}
try:
    if "-r" in sys.argv:
        a[int(sys.argv[-2])].pop(int(sys.argv[-1]))
    if "-i" in sys.argv:
        a[int(sys.argv[-3])][int(sys.argv[-2])] = float(sys.argv[-1])
except KeyError:
    a[int(sys.argv[-3])] = {}

print("DeltaT:\t\t0:\t\t1:\t\t2:\t\t3:")
max_index = 1
min_index = 0
for each in (a[0], a[1], a[2], a[3]):
    try:
        tmp = list(each.keys())
        tmp.append(max_index)
        tmp.append(min_index)
        max_index = max(tmp)
        min_index = min(tmp)
    except IOError:
        pass
for i in range(min_index, max_index + 1):
    try:
        print(i, "C\t\t", end="")
        print(round(float(a[0][i]), 2), " \t\t", end=' ')
    except:
        print("\t\t", end=' ')
    try:
        print(round(float(a[1][i]), 2), "\t\t", end=' ')
    except:
        print("\t\t", end=' ')
    try:
        print(round(float(a[2][i]), 2), "\t\t", end=' ')
    except:
        print("\t\t", end=' ')
    try:
        print(round(float(a[3][i]), 2), "\t\t")
    except:
        print("\t\t")

# WRITE TO FILE
if "-r" in sys.argv or "-i" in sys.argv:
    # Convert integer keys back to strings for JSON serialization
    data = {str(k): {str(dk): dv for dk, dv in v.items()} for k, v in a.items()}
    with open("coeficients.json", "w") as f:
        json.dump(data, f, indent=2)
