#!/usr/bin/python3
import os

directory = os.listdir("./")

data_list = []
for each in directory:
    if "data.log." in each:
        data_list.append(each)
data_list.sort()
print(data_list)
i = 1
for each in data_list:
    if "data.log." + str(i) in data_list:
        print(i)
        os.system("cat data.log." + str(i) + " >> data.log")
        os.system("rm -f data.log." + str(i))
    i += 1
