#!/bin/bash
echo stoping relevant services
sudo pkill --signal 9 airiana-core.py
sudo pkill --signal 9 httpsrv.py
sudo pkill --signal 9 controler.py
sudo pkill --signal 9 envlogger.py
sudo pkill --signal 9 alive_logger.py
echo starting aircontrol daemon
sudo nohup ./airiana-core.py daemon debug temperatur.nu humidity ping > /dev/null &
sudo nohup ./public/controler.py  >> /dev/null &

echo starting loggers
nohup ./alive_logger.py &
sudo nohup ./envlogger.py 135  >> /dev/null 2<&1 &
sudo nohup ./envlogger.py 91  >> /dev/null 2>&1 &
sudo nohup ./envlogger.py 92  >> /dev/null 2>&1 &
sudo nohup ./envlogger.py 93  >> /dev/null 2>&1 &
sleep 5
head ./RAM/out
ps ax | grep ".py"




