#!/usr/bin/python
import os
import sys
if "airiana-core.py" in sys.argv:
	os.system("sudo systemctl restart airiana.service")
	os.system("sleep 5")
	os.system("systemctl status airiana.service")
if "controller" in sys.argv:
	os.system("sudo systemctl restart controller.service")
	os.system("sleep 5")
	os.system("systemctl status controller.service")

if "status.py" in sys.argv:
	os.system("sudo pkill -15 status.py")
	os.system("sudo ./status.py & > /dev/null")

if "envlogger.py" in sys.argv:
	os.system("sudo pkill --signal 15 envlogger.py")
	os.system("sudo ./envlogger.py 135 > /dev/null &")
	os.system("sudo ./envlogger.py 91 > /dev/null &")
	os.system("sudo ./envlogger.py 92 > /dev/null &")
	os.system("sudo ./envlogger.py 93 > /dev/null &")

if "aliv_elogger.py" in sys.argv:
	os.system("sudo pkill --signal 15 alive_logger.py")
	os.system("sudo ./alive_logger.py > /dev/null &")


os.system("disown")




