#!/bin/bash
echo stoping relevant services
sudo pkill --signal 15 airiana-core.py
sudo pkill --signal 15 httpsrv.py
sudo pkill --signal 15 controler.py
echo starting aircontrol daemon
sudo nohup ./airiana-core.py daemon humidity sensors temperatur.nu debug > /dev/null &
sudo nohup ./public/controler.py  >> /dev/null &





