#!/usr/bin/python3
import os
import sys
if "airiana-core.py" in sys.argv:
	os.system("sudo systemctl start airiana.service")
if "controller" in sys.argv:
	os.system("sudo systemctl start controller.service")

if "status.py" in sys.argv:
	os.system("sudo nohup ./status.py&")

if "envlogger.py" in sys.argv:
	os.system("sudo nohup ./envlogger.py&")

if "alive_logger.py" in sys.argv:
	os.system("sudo nohup ./alive_logger.py 135&")
	os.system("sudo nohup ./alive_logger.py 91&")
	os.system("sudo nohup ./alive_logger.py 92&")
	os.system("sudo nohup ./alive_logger.py 93&")
if "http" in sys.argv:
	os.system("sudo nohup ./httpsrv.py&")





