#!/usr/bin/python3
import os
import sys
if "airiana-core.py" in sys.argv:
	os.system("sudo systemctl start airiana.service")
if "controller" in sys.argv:
	os.system("sudo systemctl start controller.service")

if "status.py" in sys.argv:
	os.system("./status.py&")

if "envlogger.py" in sys.argv:
	os.system("./envlogger.py&")

if "alive_logger.py" in sys.argv:
	os.system("./alive_logger.py 135&")
	os.system("./alive_logger.py 91&")
	os.system("./alive_logger.py 92&")
	os.system("./alive_logger.py 93&")
	os.system("./alive_logger.py 94&")
if "http" in sys.argv:
	os.system("./public/httpsrv.py&")

os.system("disown")



