#!/usr/bin/python
import os
import sys
if "airiana-core.py" in sys.argv:
	os.system("sudo systemctl stop airiana.service")
if "controller" in sys.argv:
	os.system("sudo systemctl stop controller.service")

if "status.py" in sys.argv:
	os.system("sudo pkill -15 status.py")

if "envlogger.py" in sys.argv:
	os.system("sudo pkill --signal 15 envlogger.py")

if "alive_logger.py" in sys.argv:
	os.system("sudo pkill --signal 15 alive_logger.py")
if "http" in sys.argv:
	os.system("sudo pkill --signal 15 httpsrv.py")





