#!/bin/bash
echo stop aircontroler and loggers
sudo pkill --signal 15 airiana-core.py
sudo pkill --signal 15 httpsrv.py
sudo pkill --signal 15 controler.py
sudo pkill --signal 15 envlogger.py
sudo pkill --signal 15 grapher.py

ps ax | grep .py



