#!/bin/bash

sudo systemctl stop airiana.service controller.service
cp data.log ../
cp location ../
cp data.save ../
#git pull origin
git fetch origin
git reset --hard origin/master
sudo cp ../data.log ./
sudo cp ../location ./
sudo cp ../data.save ./
rm  -f ../data.log
rm  -f ../data.save
rm  -f ../location
sudo systemctl start airiana.service controller.service
