#!/bin/bash
#Stop service
sudo systemctl stop airiana.service controller.service
#Backup config files
cp data.log ../
cp location ../
cp latlong.json ../
cp ipconfig ../
cp data.save ../
cp ha-token ../

#Get new version and reset keeping uncommitted changes
git fetch origin
git reset --mixed @{u}

#Restore config files
cp ../data.log ./
cp ../location ./
cp ../data.save ./
cp ../ha-token ./
cp ../latlong.json ./
cp ../ipconfig ./

#Remove backups
rm  -f ../data.log
rm  -f ../data.save
rm  -f ../location
rm  -f ../ha-token
rm  -f ../latlong.json
rm  -f ../ipconfig
#Start service again
sudo systemctl start airiana.service controller.service
